# Generated by Django 4.1.1 on 2022-09-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(max_length=200)),
                ('donoremail', models.CharField(max_length=200)),
                ('donorphone', models.CharField(max_length=200)),
                ('donoraddress', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
