# Generated by Django 4.1.1 on 2022-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_donor',
            old_name='donoraddress',
            new_name='donorplace',
        ),
        migrations.AlterField(
            model_name='new_donor',
            name='donoremail',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
