# Generated by Django 4.1.1 on 2022-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_donoraddress_new_donor_donorplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='donationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(max_length=100)),
                ('donation_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True)),
                ('admitted_date', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('health_conditions', models.CharField(max_length=300)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('other_informations', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
