# Generated by Django 4.1.1 on 2022-09-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
