# Generated by Django 4.1.1 on 2022-09-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_all_logins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_logins',
            old_name='donoremail',
            new_name='email',
        ),
    ]
