# Generated by Django 4.1.1 on 2022-10-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_donoremail_all_logins_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orphan',
            options={'ordering': ('name',), 'verbose_name': 'orphan', 'verbose_name_plural': 'orphans'},
        ),
    ]
