# Generated by Django 4.1.1 on 2022-10-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_district_orphanage_delete_donationtype_delete_orphan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orphanage',
        ),
    ]
