# Generated by Django 4.1.1 on 2022-10-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_orphanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.IntegerField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=12)),
                ('image', models.ImageField(upload_to='pics')),
                ('no_of_persons', models.IntegerField(max_length=10)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.district')),
            ],
        ),
    ]
