# Generated by Django 4.1.1 on 2022-10-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_orphanage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orphanage',
        ),
    ]
