# Generated by Django 4.1.1 on 2022-10-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_donationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtype',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
