# Generated by Django 4.1.1 on 2022-10-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_donationtype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(max_length=250)),
                ('pin', models.CharField(max_length=250)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.donationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.all_logins')),
            ],
        ),
    ]
