# Generated by Django 4.1.1 on 2022-10-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_userdonate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonate',
            name='hname',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
