# Generated by Django 4.1.1 on 2022-10-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_userdonate_district_alter_userdonate_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonate',
            name='item',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='home.donationtype'),
        ),
    ]
