# Generated by Django 4.1.1 on 2022-11-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_userdonate_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donorprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('hname', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.all_logins')),
            ],
        ),
    ]
